version: '3.7'

services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /root/app
    working_dir: /root/app
    environment:
     - CHAT_GPT_API_KEY=${CHAT_GPT_API_KEY}
    entrypoint: bash
    stdin_open: true
    tty: true
    ports:
      - 9090:9090
