version: '3.7'

services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /root/app
    working_dir: /root/app
    entrypoint: bash
    stdin_open: true
    tty: true
    ports:
      - 9090:9090
